[Design] Login View & SplachView 생성
Swift-Coding-Club/Team_Nav pull request #11
Opened 2022-11-05 05:01 UTC by LiSeul

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- LoginView 추가
- SplachView 추가

## Key Changes 🔥 (주요 구현/변경 사항)\
View 추가

## ToDo 📆 (남은 작업)
- [ ] 로그인 API 작업 진행 
- [ ] SplachView 연결

## ScreenShot 📷 (참고 사
<img width="381" alt="스크린샷 2022-11-05 오후 1 59 52" src="https://user-images.githubusercontent.com/40952628/200102015-032643d5-12dd-4155-a70b-80e09d983acf.png">
<img width="389" alt="스크린샷 2022-11-05 오후 1 59 36" src="https://user-images.githubusercontent.com/40952628/200102016-da32c8a2-0369-4350-aa61-39b634460eba.png">
진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
간단한 레이아웃 추가입니다. 가볍게 리뷰하셔도 좋습니다.
해당 뷰에 기능을 추가하실 분들은 꼼꼼한 리뷰도 좋습니다.

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #No.

2022-11-05 05:14 UTC, taek0622 requested changes
고생하셨습니다.
SwiftUI가 처음이시라 2개의 뷰를 만드는게 많이 힘드셨을텐데, 정말 고생하셨어요.
몇가지 수정이 필요해 보이는 부분 리뷰 남겼습니다.
확인 부탁드려요~

2022-11-05 05:14 UTC, taek0622 commented on Nav/LoginView.swift
> +                    //Splash
p5;
불필요한 주석이라면 삭제가 필요할 것 같습니다.
혹시 영역을 구분하기 위한 주석이라면 `// MARK: - Splash`를,
나중에 작업하기 위한 부분을 위한 주석이라면`// TODO: - Splash 추가` 처럼 사용하시면 더 좋을 것 같아요.

2022-11-05 05:14 UTC, taek0622 commented on Nav/SplachView.swift
> +                ZStack{
p1;
불필요한 ZStack이 중첩된 것 같습니다.
특별히 필요한 것이 아니라면 하나 삭제 부탁드려요.

2022-11-05 05:14 UTC, taek0622 commented on Nav/LoginView.swift
> +                    ZStack{
p1;
불필요한 ZStack이 3중첩되어 있습니다.
정말 필요한 동작인지 다시 한번 생각해보시고 필요하지 않다면 중첩은 피하는 것이 좋을 것 같습니다.

2022-11-05 05:14 UTC, taek0622 commented on Nav/LoginView.swift
> +                        LinearGradient(gradient: Gradient(colors: [Color.primaryRed, Color.secondaryOrange]), startPoint: .top, endPoint: .bottom)
p2;
스플래시의 상단은 `primaryRed`가 아니라 `redBean` 컬러입니다. 수정 부탁드려요~

2022-11-05 05:14 UTC, taek0622 commented on Nav/LoginView.swift
> +                        )
p1;
사용되지 않는 sheet인 것 같습니다.
실험용 코드라면 삭제하고 올려주시면 감사하겠습니다~

2022-11-05 05:14 UTC, taek0622 commented on Nav/LoginView.swift
> +                        .padding(2)
p5;
apple login의 경우 따로 이렇게 버튼을 만들지 않아도 Apple Login 자체 기능에 버튼을 만들어주는 기능이 있는 것으로 알고 있습니다.
특별히 커스텀이 필요한 버튼이라면 이렇게 만들어주셔도 무관하지만, 애플 로그인에서 자체 제공하는 버튼을 사용해보시는 건 어떨까요?

2022-11-05 05:14 UTC, taek0622 commented on Nav/LoginView.swift
> +                        .padding(2)
p2;
현재 4개의 버튼이 비슷한 모양을 재사용하고 있습니다.
3번 이상 반복되는 컴포넌트들은 별도로 내부 코드를 빼서 재사용하는 것이 더 좋을 것 같습니다.

2022-11-14 13:38 UTC, LiSeul commented on Nav/LoginView.swift
> +                    //Splash
넵! Mark: Splash 로변경하겠습니다.

2022-11-14 13:39 UTC, LiSeul commented on Nav/SplachView.swift
> +                ZStack{
넵 감사합니다 :)

2022-11-14 13:40 UTC, LiSeul commented on Nav/LoginView.swift
> +                    ZStack{
넵 중첩 된 Ztack 변경하겠습니다.

2023-05-12 10:38 UTC, closed without merging