Delete Image
Swift-Coding-Club/Team_Nav pull request #19
Opened 2022-11-26 05:33 UTC by Shin-Yu-1

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
사진 선택하여 추가했으나 취소 하고자 코드 추가

## Key Changes 🔥 (주요 구현/변경 사항)
추가된 사진에 버튼 추가

## ToDo 📆 (남은 작업)
- 생각이 안 납니다

## ScreenShot 📷 (참고 사진)
<img width="320" alt="스크린샷 2022-11-26 오후 2 32 42" src="https://user-images.githubusercontent.com/82097725/204073826-1cb62fac-6b46-44bd-9244-813acd748bab.png">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
사진 터치 시 사라지도록 만들었습니다.

## Reference 🔗
없음

## Close Issues 🔒 (닫을 Issue)
Close #No.

2022-11-27 02:52 UTC, taek0622 requested changes
고생하셨습니다.
리뷰가 좀 늦어졌는데, 수정이 필요해보이는 부분 리뷰 남겼습니다.
확인 부탁드려요.

2022-11-27 02:52 UTC, ikanic commented on Nav/Model/MockDatum.swift
> +}
p2;
개발단계에서 사용된 주석은 삭제 후에 올려주시면 더 좋을 것 같습니다.
꼭 주석이 필요하다면 `// MARK: -` 로 달아주시면 좋을 것 같아요.

2022-11-27 02:52 UTC, ikanic commented on Nav/View/PinCreationView.swift
> +    let rouws = [GridItem()]
p2;
변수 이름이 무엇을 뜻하는지 명확하지 못한 것 같습니다.
만약에 행을 뜻하는 것이라면`rows`라는 이름이 좋을 것 같아요.

2022-11-27 02:52 UTC, ikanic commented on Nav/View/PinCreationView.swift
> +                        UIScrollView.appearance().bounces = true
오 이렇게하면 스크롤 뷰의 바운들들 없앨 수 있군요.
리아 덕분에 좋은 인사이트 하나 얻어갑니다. 리아 최고~!

2022-11-27 02:52 UTC, taek0622 commented on Nav/View/PinCreationView.swift
> +                            .frame(width: 100, height: 100)
p1;
현재 이곳에서 준 Frame이 정상적으로 작동하지 않고 있는 것 같습니다.
원인 파악 및 수정이 필요할 것 같아요.

2022-12-03 07:05 UTC, Shin-Yu-1 commented on Nav/View/PinCreationView.swift
> +    let rouws = [GridItem()]
오타였어여!!! u 뺄게요

2023-05-12 10:41 UTC, tawans commented
고생하셨습니다

2023-05-12 10:41 UTC, closed without merging