Feat✨: #35 Add Picture Add Delete
Swift-Coding-Club/Team_Nav pull request #36
Opened 2023-06-02 09:26 UTC by tawans

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
핀 추가 View 에서 사진 추가 및 변경을 하기위해 기능 추가
## Key Changes 🔥 (주요 구현/변경 사항)
핀 추가 View 에서 사진 추가 및 변경 코드 추가
## ToDo 📆 (남은 작업)
- [ ] 실제 사진 추가했을때 DB에 저장되고 DB에서 삭제되는 로직을 추가해야함 
- [ ] 직관적으로 추가 삭제만 할 것인지 니면 변경하는 식으로 수정할 지 토론 필요
## ScreenShot 📷 (참고 사진)
![Simulator Screenshot - iPhone 14 Pro - 2023-06-02 at 18 24 25](https://github.com/Swift-Coding-Club/Team_Nav/assets/33337450/d096c188-8c37-46fc-bf87-2104e1e8d0ae)
![Simulator Screenshot - iPhone 14 Pro - 2023-06-02 at 18 24 31](https://github.com/Swift-Coding-Club/Team_Nav/assets/33337450/adefc710-78d0-4cc4-8113-cd391236b783)
## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
사진 추가 및 변경 삭제 에 관하여 회의 시간에 논의 해보죱
## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #35 .

2023-06-08 10:37 UTC, taek0622 requested changes
고생하셨습니다.
일부 수정이 필요해 보이는 부분과 질문 사항 코멘트로 남겼습니다. 확인 부탁드려요~
또, 현재 UI가 버튼이 이미지의 아예 아래로 크게 잡히는데, 이로 인해 깨지는 UI도 수정되어야 할 것 같네요.

2023-06-08 10:37 UTC, taek0622 commented on Nav/View/PinCreationView.swift
> +                                        .clipped()
Q.
`clipped`를 넣은 이유가 있을까요?
현재 해당 부분이 없어도 동일한 동작을 하는 것처럼 보입니다.

2023-06-08 10:37 UTC, taek0622 commented on Nav/View/PinCreationView.swift
> +                            VStack {
Q.
해당 부분에 `VStack`이 추가된 이유가 무엇일까요?
VStack을 지워봐도 같은 동작을 하네요.

2023-06-08 10:37 UTC, taek0622 commented on Nav/View/PinCreationView.swift
> +                                }
p2;
103번째 줄 Button 부터 전체적으로 수정하는 것이 좋을 것 같습니다.
해당 부분이 동작하는 방식이 PhotosPicker로 인한 것으로 보이는데, 그렇다면 상위에 있는 103번째 줄의 Button은 아무 동작도 하지 않게 되네요.
PhotosPicker를 밖으로 빼고 그 안에 Image를 통해 모양을 잡는 것이 좋을 것 같습니다.

2023-06-08 10:37 UTC, taek0622 commented on Nav/View/PinCreationView.swift
> +    @State private var selectedImageIndex: Int? = nil;
가능하다면 Index를 다루는 변수는 하나로 합치면 좋을 것 같네요.

2023-07-15 08:26 UTC, tawans commented on Nav/View/PinCreationView.swift
> +                                        .clipped()
코멘트 주셨듯이 같은 동작을 하여서 불필요한 코드로 삭제하였습니다.

2023-07-15 08:29 UTC, tawans commented on Nav/View/PinCreationView.swift
> +                            VStack {
코멘트 주셨듯이 같은 동작을 하여서 불필요한 코드로 삭제하였습니다.

2023-07-15 08:43 UTC, tawans commented on Nav/View/PinCreationView.swift
> +                                }
동작하지 않는 Button은 제거하였고 ZStack 을 이용하여 minus버튼 그림 중간으로 넣었습니다.

2023-07-15 08:46 UTC, tawans commented on Nav/View/PinCreationView.swift
> +    @State private var selectedImageIndex: Int? = nil;
selectedImageIndex 로 인덱스 합쳤습니다.

2024-09-03 04:29 UTC, closed without merging